
default: &default
  adapter: postgresql
  username:
  password:
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: mk-tracker-dev

test:
  <<: *default
  database: mk-tracker-test
