AdminUser.create(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

# Create the 4 users
User.find_or_create_by!(username: 'Jan')
User.find_or_create_by!(username: 'Pablo')
User.find_or_create_by!(username: 'Vita')
User.find_or_create_by!(username: 'Xime')

# Create the 48 tracks
Track.find_or_create_by!(name: 'Animal Crossing')
Track.find_or_create_by!(name: 'Baby Park (GCN)')
Track.find_or_create_by!(name: 'Big Blue')
Track.find_or_create_by!(name: 'Bone Dry Dunes')
Track.find_or_create_by!(name: 'Bowser’s Castle')
Track.find_or_create_by!(name: 'Cheep Cheep Beach (DS)')
Track.find_or_create_by!(name: 'Cheese Land (GBA)')
Track.find_or_create_by!(name: 'Cloudtop Cruise')
Track.find_or_create_by!(name: 'DK Jungle (3DS)')
Track.find_or_create_by!(name: 'Dolphin Shoals')
Track.find_or_create_by!(name: 'Donut Plains 3 (SNES)')
Track.find_or_create_by!(name: 'Dragon Driftway')
Track.find_or_create_by!(name: 'Dry Dry Desert (GCN)')
Track.find_or_create_by!(name: 'Electrodrome')
Track.find_or_create_by!(name: 'Excitebike Arena')
Track.find_or_create_by!(name: 'Grumble Volcano (Wii)')
Track.find_or_create_by!(name: 'Hyrule Circuit')
Track.find_or_create_by!(name: 'Ice Ice Outpost')
Track.find_or_create_by!(name: 'Koopa City (3DS)')
Track.find_or_create_by!(name: 'Mario Circuit')
Track.find_or_create_by!(name: 'Mario Circuit (GBA)')
Track.find_or_create_by!(name: 'Mario Kart Stadium')
Track.find_or_create_by!(name: 'Melody Motorway (3DS)')
Track.find_or_create_by!(name: 'Moo Moo Meadows (Wii)')
Track.find_or_create_by!(name: 'Mount Wario')
Track.find_or_create_by!(name: 'Mute City')
Track.find_or_create_by!(name: 'Piranhna Plant Pipeway (3DS)')
Track.find_or_create_by!(name: 'Rainbow Road')
Track.find_or_create_by!(name: 'Rainbow Road (N64)')
Track.find_or_create_by!(name: 'Rainbow Road (SNES)')
Track.find_or_create_by!(name: 'Ribbon Road (GBA)')
Track.find_or_create_by!(name: 'Royal Raceway (N64)')
Track.find_or_create_by!(name: 'Sherbet Land (GCN)')
Track.find_or_create_by!(name: 'Shy Guy Falls')
Track.find_or_create_by!(name: 'Sunshine Airport')
Track.find_or_create_by!(name: 'Super Bell Subway')
Track.find_or_create_by!(name: 'Sweet Sweet Canyon')
Track.find_or_create_by!(name: 'Thwomp Ruins')
Track.find_or_create_by!(name: 'Tick-Tock Clock (DS)')
Track.find_or_create_by!(name: 'Toad Harbour')
Track.find_or_create_by!(name: 'Toad’s Turnpike (N64)')
Track.find_or_create_by!(name: 'Twisted Mansion')
Track.find_or_create_by!(name: 'Wario Stadium (DS)')
Track.find_or_create_by!(name: 'Wario’s Goldmine (Wii)')
Track.find_or_create_by!(name: 'Water Park')
Track.find_or_create_by!(name: 'Wild Woods')
Track.find_or_create_by!(name: 'Yoshi Circuit (GCN)')
Track.find_or_create_by!(name: 'Yoshi Valley (N64)')


